language: go
go:
  - "1.11"

sudo: true

services:
- docker

env:
  global:
    - GO111MODULE=on
    - DOCKER_REPOSITORY=braindoctor/clustercode-worker
  matrix:
    - GOOS=linux GOARCH=amd64 DOCKER_ARCH=amd64-edge DOCKER_TAG=amd64
    - GOOS=linux GOARCH=arm   DOCKER_ARCH=armhf-edge DOCKER_TAG=armhf
    - GOOS=linux GOARCH=arm64 DOCKER_ARCH=arm64-edge DOCKER_TAG=arm64

stages:
- name: unit test
- name: docker build
  if: (type == pull_request)
  # if: (branch = master) AND (type != pull_request)
- name: docker release
  if: (tag IS present) OR (branch =~ /^((origin\/)?master|(origin\/)?release-\d+\.\d+)$/)

jobs:
  include:
  - stage: unit test
    script: go test ./...

  - stage: docker build
    script: .travis/docker-build.sh

  - stage: docker release
    script: .travis/docker-build.sh
    deploy:
    - provider: script
      script: .travis/docker-release.sh
      #on:
      #  all_branches: true
