name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Register qemu for multiarch build
      run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: check if experimental are enabled
      run: docker manifest
    - name: Build the Docker image
      run: docker build . -t docker.io/braindoctor/clustercode-worker:${GITHUB_REF:-latest}
 
