---
name: Docker Image CI

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint YAML files
      run: docker run --rm -v $(pwd):/data cytopia/yamllint .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps:
    - uses: actions/checkout@v1
    - name: Register qemu for multiarch build
      run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - name: Build the Docker image
      run: docker build . -t docker.io/braindoctor/clustercode-worker:${GITHUB_REF##*/}
