---
name: Release CI

on:
  push:
    branches:
    - master
    tags:
    - "*"

env:
  REGISTRY_IMAGE: docker.io/braindoctor/clustercode-worker

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint YAML files
      run: docker run --rm -v $(pwd):/data docker.io/cytopia/yamllint .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: ${{ runner.os }}-go
    - name: Run unit tests
      run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps:
    - uses: actions/checkout@v1
    - name: Register qemu for multiarch build
      run: docker run --rm --privileged docker.io/multiarch/qemu-user-static:register --reset
    - name: Build Docker image
      run: >
        docker build
        --tag ${REGISTRY_IMAGE}:${GITHUB_REF##*/}
        --build-arg VERSION=${GITHUB_REF##*/}
        --build-arg GIT_COMMIT=${GITHUB_SHA:-unknown}
        .
    - name: Login to Docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push Docker image
      run: docker push ${REGISTRY_IMAGE}:${GITHUB_REF##*/}

  release:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: ${{ runner.os }}-go
    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
