---
name: Test

on:
  push:
    branches-ignore:
    - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint YAML files
      run: docker run --rm -v $(pwd):/data docker.io/cytopia/yamllint .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: go test ./...
